version: '3'
services:
  database:
    image: "postgres"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: 'rm'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'cat_test_db'
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  pgdata:
