language: node_js
node_js:
  - 10
  - 12
install: npm install
script:
  - "npm run test -- complex-sample"
  - "npm run test -- simple-sample"
  - "npm run test -- typeorm-graphql-sample"
  - "npm run test -- typeorm-sample"
