language: node_js
install: npm install
script:
  - "npm run test -- complex-sample"
  - "npm run test -- simple-sample"
  - "npm run test -- typeorm-graphql-sample"
  - "npm run test -- typeorm-sample"
