name: 'Auto Rebase'
on:
  issue_comment:
    types: [created]
jobs:
  auto_rebase:
    name: Auto Rebase
    needs: e2e
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Automatic Rebase
      uses: cirrus-actions/rebase@1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
