name: CRON Job

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]
        app-name:
          [
            simple-sample,
            complex-sample,
            cqrs-sample,
            mongo-sample,
            typeorm-sample,
            websocket-sample,
            rxjs-sample,
            render-sample,
            graphql-sample,
            microservice-sample,
          ]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
      - name: npm test
        run: npm run test:cov -- ${{ matrix.app-name }}

  e2e:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start Docker-Compose
        run: docker-compose up -d
      - name: npm install
        run: npm ci
      - name: Run tests
        run: ./scripts/full-e2e
      - name: Stop Docker-Compose
        run: docker-compose down
