name: Node CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        sample-name: [complex-sample, simple-sample, typeorm-sample, typeorm-graphql-sample]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm ci
    - name: npm test
      run: npm test -- ${{ matrix.sample-name }}
      env:
        CI: true
